name: Build

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # dependencies
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true
          version: 1.7.0

      - name: goreleaser info
        run: goreleaser -v

      - name: task
        uses: arduino/setup-task@v1

      - name: task info
        run: task --version

      - name: qemu
        if: github.event.pull_request.head.repo.fork == false
        uses: docker/setup-qemu-action@v2

      - name: buildx
        if: github.event.pull_request.head.repo.fork == false
        uses: docker/setup-buildx-action@v2

      # checkout
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup go
      - name: go
        uses: actions/setup-go@v3
        with:
          go-version: 1.25

      - name: go info
        run: |
          go version
          go env

      # cache
      - name: cache-go
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-mod

      - name: cache-task
        uses: actions/cache@v3
        with:
          path: .task/**/*
          key: ${{ runner.os }}-go-task

      # vendor
      - name: vendor
        run: |
          task vendor

      # test
      - name: tests
        run: |
          task test

      # git status
      - name: git status
        run: git status

      # build/release reqs
      - name: branch name
        id: branch-names
        uses: tj-actions/branch-names@v9
        with:
          replace_slashes_with_hyphens: "true"
          strip_tag_prefix: "v"

      # build
      - name: build
        if: steps.branch-names.outputs.is_tag == 'false'
        run: |
          task snapshot

      # publish
      - name: publish
        if: steps.branch-names.outputs.is_tag == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          task publish

      # artifacts
      - name: artifact_linux
        uses: actions/upload-artifact@v4
        with:
          name: build_linux
          path: dist/*linux*

      - name: artifact_darwin
        uses: actions/upload-artifact@v4
        with:
          name: build_darwin
          path: dist/*darwin*

      # docker login
      - name: docker login
        if: github.event.pull_request.head.repo.fork == false
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      # docker build (latest & tag)
      - name: docker - build release
        if: steps.branch-names.outputs.is_tag == 'true' && github.event.pull_request.head.repo.fork == false
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          pull: true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            l3uddz/autoscan:${{ steps.branch-names.outputs.tag }}
            l3uddz/autoscan:latest

      # docker build (branch)
      - name: docker - build branch
        if: steps.branch-names.outputs.is_tag == 'false' && github.event.pull_request.head.repo.fork == false
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          pull: true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            l3uddz/autoscan:${{ steps.branch-names.outputs.current_branch }}

      # cleanup
      - name: cleanup
        if: github.event.pull_request.head.repo.fork == false
        run: |
          rm -f ${HOME}/.docker/config.json
